version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - overlay
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:80"
    networks:
      - overlay

networks: 
  overlay:
